# Generated by Django 5.1.6 on 2025-04-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
